<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.16">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alec Loudenback">
<meta name="dcterms.date" content="2026-05-21">
<meta name="description" content="JuliaActuary is an ecosystem of packages that makes Julia the easiest language to get started for actuarial workflows.">

<title>FinanceModels vs QuantLib: where Julia closes the gap – JuliaActuary</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//assets/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a0731b9a3a5d496010872d775e5d9bc3.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a9c66334b43f472998d4f0687f28726e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="stylesheet" href="../../assets/highlight/styles/github.min.css">
<script src="../../assets/highlight/highlight.min.js"></script>
<script src="../../assets/highlight/languages/julia.min.js"></script>
<script src="../../assets/highlight/languages/julia-repl.min.js"></script>
<script src="../../assets/highlight/languages/python.min.js"></script>
<script src="../../assets/highlight/languages/r.min.js"></script>
<script>hljs.highlightAll();</script>
<script data-goatcounter="https://juliaactuary.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logos/android-chrome-512x512.png" alt="JuliaActuary Logo" class="navbar-logo light-content">
    <img src="../../assets/logos/android-chrome-512x512.png" alt="JuliaActuary Logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">JuliaActuary</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../packages.html"> 
<span class="menu-text">Packages</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../learn.html"> 
<span class="menu-text">Learn</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../examples.html"> 
<span class="menu-text">Examples</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../benchmarks.html"> 
<span class="menu-text">Benchmarks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../community.html"> 
<span class="menu-text">Community</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JuliaActuary"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../all-posts.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">FinanceModels vs QuantLib: where Julia closes the gap</h1>
                  <div>
        <div class="description">
          JuliaActuary is an ecosystem of packages that makes Julia the easiest language to get started for actuarial workflows.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">blog</div>
                <div class="quarto-category">code</div>
                <div class="quarto-category">autodiff</div>
                <div class="quarto-category">finance</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Alec Loudenback </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>One question that I try to explain sometimes is the purpose of actuarial modeling and financial projections in the actuarial context. It genuinely is different than the “quant” perspective where valuations of individual assets is of the utmost importance. In contrast, in actuarial projections, financial reporting, internal forecasting, capital management, and other non-trading-desk activities typically trade precision for comprehensiveness and completeness. A massive portfolio of 100,000 annuity contracts supported by ~1,000 assets doesn’t need to be valued to the last cent, but doing a multi-basis forecast still requires accuracy and robustness. For this reason, actuarial models and trading portfolio models share many aspects but they do differ in design trade-offs to achieve different goals.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="venn-capability-overlap.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Capability overlap between actuarial and quant models, by engine performance.</figcaption>
</figure>
</div>
<section id="example-fixed-bond-analytics." class="level2">
<h2 class="anchored" data-anchor-id="example-fixed-bond-analytics.">Example: Fixed Bond Analytics.</h2>
<p>Most bond analytics is a cashflow vector and a yield curve. Price, duration, convexity, key-rate durations, sensitivity to a calibrated curve, arbitrary-precision validation — all of those are things you <em>decide</em> to compute from those two inputs. The interesting design question is how much code each decision costs, and how much new machinery each new computation requires.</p>
<p>For the workflows it covers, <a href="https://juliaactuary.org">JuliaActuary</a>’s answer is: not much, and almost none. A small vocabulary of primitives — <code>pv</code>, <code>duration</code>, <code>convexity</code>, <code>sensitivities</code>, the curve constructors. These compose together to provide a very generic and efficient set of tools to analyze asset and liabilities. Generic numeric types flow through them; <code>ForwardDiff</code> walks whatever derivative you need out of the same code. The cashflow vector built once at the top of this post threads through every example below.</p>
<p><a href="https://www.quantlib.org/">QuantLib</a> appears throughout as a reference — the <em>de facto</em> open-source standard for quantitative finance, 25 years old, the implementation most other libraries get cross-checked against. The two libraries also have noticeably different design centers. QuantLib aims for <em>trading-desks</em>: settlement conventions, holiday calendars, market-specific pricing engines — the machinery you need when a counterparty is going to send you a cash transfer next Tuesday and the answer has to match the exact figure their bond admin system prints. JuliaActuary is <em>projection-flavored</em>: cashflows and curves as composable values, generic numeric types so that sensitivities and stochastic shocks flow through naturally, calibration as ordinary optimization. There is quite a bit of overlap in capabilities and quite a bit of Quantlib’s surface area can be accurately recrated using Julia and JuliaActuary’s functionality.</p>
</section>
<section id="the-cashflow-vector" class="level2">
<h2 class="anchored" data-anchor-id="the-cashflow-vector">The cashflow vector</h2>
<p>A 5-year, 4% semi-annual-coupon bond at a flat 3% continuously-compounded yield. Once the vector exists, price and duration are one function call each.</p>
<div id="4" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>using FinanceCore
using FinanceCore: Continuous, Periodic
using FinanceModels
using FinanceModels: Spline
using ActuaryUtilities
using Printf

coupon_rate = 0.04
maturity_years = 5
freq_per_year = 2
par = 100.0

# A simple upward-sloping zero curve. The t = 0 anchor lines up with QL's
# ZeroCurve boundary so both libraries are pricing against an identical grid.
tenors = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 7.0]
base_zeros = [0.025, 0.025, 0.027, 0.029, 0.030, 0.032, 0.034]
curve = FinanceModels.ZeroRateCurve(base_zeros, tenors, Spline.Linear())

bond = FinanceModels.Bond.Fixed(coupon_rate, Periodic(freq_per_year), maturity_years)
cfs = collect(bond)

price = FinanceCore.pv(curve, cfs) * par
mod_dur = duration(Modified(), curve, cfs)

(price=price, modified=mod_dur)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(price = 103.67817922167015, modified = 4.587323550496468)</code></pre>
</div>
</div>
<p>QuantLib’s setup is longer — a <code>Schedule</code>, a <code>FixedRateBond</code>, a <code>FlatForward</code> curve, a <code>DiscountingBondEngine</code>, a <code>setPricingEngine</code> call — but it produces the same number:</p>
<pre class="python"><code># Python — QuantLib via SWIG bindings
import QuantLib as ql

settle    = ql.Date(1, 1, 2026)
maturity  = ql.Date(1, 1, 2031)
day_count = ql.Thirty360(ql.Thirty360.BondBasis)

schedule = ql.Schedule(settle, maturity, ql.Period(ql.Semiannual),
                       ql.NullCalendar(), ql.Unadjusted, ql.Unadjusted,
                       ql.DateGeneration.Backward, False)
bond     = ql.FixedRateBond(0, 100.0, schedule, [0.04], day_count)

pillar_dates = [settle + ql.Period(y, ql.Years) for y in [0, 1, 2, 3, 4, 5, 7]]
zeros        = [0.025, 0.025, 0.027, 0.029, 0.030, 0.032, 0.034]
curve = ql.ZeroCurve(pillar_dates, zeros, day_count, ql.NullCalendar(),
                     ql.Linear(), ql.Continuous)
bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(curve)))

print(bond.NPV())  # → 103.6781792217</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 43%">
<col style="width: 24%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>metric</th>
<th>FinanceModels / ActuaryUtilities</th>
<th>QuantLib (Python)</th>
<th>diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Price</td>
<td>103.6781792217</td>
<td>103.6781792217</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>Modified duration</td>
<td>4.5873235505</td>
<td>4.5873235505</td>
<td>0.00</td>
</tr>
</tbody>
</table>
<p>The interesting part is what the same <code>cfs</code> is about to do without writing any new code.</p>
</section>
<section id="modified-duration-is-the-derivative" class="level2">
<h2 class="anchored" data-anchor-id="modified-duration-is-the-derivative">Modified duration is the derivative</h2>
<p>Modified duration is, definitionally, a derivative: <code>−d(log P)/dy</code>. In FinanceModels, that’s exactly what’s written down:</p>
<pre class="julia"><code>function duration(yield, valuation_function)
    D(i) = log(valuation_function(i + yield))
    return -ForwardDiff.derivative(D, 0.0)
end</code></pre>
<p>That’s the whole function. No shift size, no central-difference formula, no special-casing the compounding convention — <code>ForwardDiff.derivative</code> walks the analytic derivative through whatever sequence of operations <code>pv</code> performed, and out comes the exact gradient.</p>
<p>The contrast with bump-and-reprice is visible if you ask the same question both ways:</p>
<div id="6" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>mod_ad = duration(Modified(), curve, cfs)

# Parallel-shift the term-structured curve by `shift` at every pillar.
function mod_finite_diff(shift)
    yield_up = FinanceModels.ZeroRateCurve(base_zeros .+ shift, tenors, Spline.Linear())
    yield_dn = FinanceModels.ZeroRateCurve(base_zeros .- shift, tenors, Spline.Linear())
    p_up = FinanceCore.pv(yield_up, cfs)
    p_dn = FinanceCore.pv(yield_dn, cfs)
    p = FinanceCore.pv(curve, cfs)
    return (p_dn - p_up) / (2 * shift * p)
end

for h in (1e-2, 1e-4, 1e-6, 1e-8, 1e-10, 1e-12, 1e-14)
    fd = mod_finite_diff(h)
    err = abs(fd - mod_ad)
    @printf("shift = %.0e   mod (FD) = %.12f   |err vs AD| = %.2e\n", h, fd, err)
end
@printf("                   mod (AD) = %.12f\n", mod_ad)</code></pre>
<div class="cell-output cell-output-stdout">
<pre><code>shift = 1e-02   mod (FD) = 4.589142977807   |err vs AD| = 1.82e-03
shift = 1e-04   mod (FD) = 4.587323732417   |err vs AD| = 1.82e-07
shift = 1e-06   mod (FD) = 4.587323550561   |err vs AD| = 6.49e-11
shift = 1e-08   mod (FD) = 4.587323557950   |err vs AD| = 7.45e-09
shift = 1e-10   mod (FD) = 4.587323354491   |err vs AD| = 1.96e-07
shift = 1e-12   mod (FD) = 4.587353337893   |err vs AD| = 2.98e-05
shift = 1e-14   mod (FD) = 4.583177078405   |err vs AD| = 4.15e-03
                   mod (AD) = 4.587323550496</code></pre>
</div>
</div>
<p>For shifts in the 1e-4 to 1e-6 range, the finite-difference answer agrees with AD to six or seven figures — fine for most reporting. Push the shift down further and floating-point cancellation takes over: at 1e-12 the FD answer is <em>less</em> accurate than at 1e-4. There is no shift size that recovers the AD answer.</p>
<p>Six-figure agreement is enough for the standard duration report you ship to a quarterly committee, so AD’s accuracy on this number is overkill. The bigger win shows up in pipelines that compose multiple derivatives — calibration objectives, optimization gradients, hedge ratios, Greeks for non-Black-Scholes payoffs — all from the same <code>ForwardDiff.derivative</code> call applied to the price function, with no shift-size choice propagating up the chain.</p>
</section>
<section id="convexity-is-the-next-derivative" class="level2">
<h2 class="anchored" data-anchor-id="convexity-is-the-next-derivative">Convexity is the next derivative</h2>
<p>Convexity is <code>(d²P/dy²) / P</code>. QL’s <code>BondFunctions.convexity</code> takes a <em>scalar</em> <code>InterestRate</code>, not a yield curve, so for this convention comparison both sides drop down to a flat 3% reference yield. Same bond, same cashflow vector — only the discounting model is flat instead of term-structured:</p>
<div id="8" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>yield_flat = FinanceModels.Yield.Constant(Continuous(0.03))
convex = convexity(yield_flat, cfs)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>26.820500017954323</code></pre>
</div>
</div>
<p>QuantLib has a native <code>BondFunctions.convexity</code>:</p>
<pre class="python"><code># Python — QuantLib
y_ann = math.exp(0.03) - 1                  # annual-effective equiv. of 3% cont.
ir    = ql.InterestRate(y_ann, day_count, ql.Compounded, ql.Annual)
convex_quantlib = ql.BondFunctions.convexity(bond, ir)   # → 25.2585956899</code></pre>
<p>They report different numbers — exactly <code>(1+y)²</code> apart — because they use different conventions:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>metric</th>
<th style="text-align: right;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ActuaryUtilities.convexity</code> (“Macaulay”)</td>
<td style="text-align: right;">26.8205000</td>
</tr>
<tr class="even">
<td><code>QuantLib.BondFunctions.convexity</code> (“modified”)</td>
<td style="text-align: right;">25.2585957</td>
</tr>
<tr class="odd">
<td>QL × <code>(1 + y_ann)²</code></td>
<td style="text-align: right;">26.8205000</td>
</tr>
</tbody>
</table>
<p>QuantLib normalizes by <code>(1+y)²</code> — the extra chain-rule factor that drops out when you differentiate against the <em>periodic</em> yield. That’s “modified convexity” in the discrete-compounding sense. ActuaryUtilities reports the unnormalized second moment of cashflow times — the convexity that Bloomberg and most actuarial references show. Neither is wrong; both show up in industry. The conversion is a single multiplication.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Under the hood: how <code>convexity</code> works (and how to write your own convention)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>convexity(yield, cfs)</code> is internally a nested pair of <code>ForwardDiff.derivative</code> calls. Roughly:</p>
<pre class="julia"><code>function convexity(yield, cfs)
    v(x) = abs(price(yield + x, cfs))
    ∂²P  = ForwardDiff.derivative(y -&gt; ForwardDiff.derivative(v, y), 0.0)
    return ∂²P / v(0.0)
end</code></pre>
<p>The shock convention is set by how <code>yield + Δ</code> is defined for the yield type. For <code>Yield.Constant{Continuous}</code>, <code>+</code> uses <code>log1p</code> semantics so <code>Δ</code> is interpreted as a <em>periodic</em>-rate shock — which gives Macaulay-style <code>t·(t+1)</code> convexity. For a continuous-rate convexity instead, write the AD call directly against your own parameterization:</p>
<div id="10" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>using ForwardDiff

function price_at_continuous(y)
    yc = FinanceModels.Yield.Constant(Continuous(y))
    return FinanceCore.pv(yc, cfs)
end

ytm_flat = 0.03
P0 = price_at_continuous(ytm_flat)
convex_cont = ForwardDiff.derivative(
    y -&gt; ForwardDiff.derivative(price_at_continuous, y), ytm_flat) / P0</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>22.228284058748308</code></pre>
</div>
</div>
<p>This gives the continuous-shock convexity (<code>Σ t²·cf·df / P</code>), which differs from the library’s <code>convexity</code> by exactly one Modified duration:</p>
<div id="12" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>mod_flat = duration(Modified(), yield_flat, cfs)
(convex_cont, convex - convex_cont, mod_flat)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(22.228284058748308, 4.592215959206015, 4.592215959206014)</code></pre>
</div>
</div>
<p>The same AD machinery extends to any derivative order or shock convention — write the parameterization, call <code>ForwardDiff.derivative</code> (or <code>.gradient</code>, or <code>.hessian</code>), nest as deep as you want.</p>
</div>
</div>
</div>
</section>
<section id="key-rate-durations-decompose-the-derivative" class="level2">
<h2 class="anchored" data-anchor-id="key-rate-durations-decompose-the-derivative">Key-rate durations decompose the derivative</h2>
<p>KRDs come from Thomas Ho’s 1992 paper — <em>the</em> standard ALM sensitivity decomposition: shift the zero curve by a tent function centered at each key tenor, measure the price change, sum across pillars to recover the modified duration. ActuaryUtilities ships the tent bumper.</p>
<div id="14" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>krd_pillars = collect(1.0:1.0:10.0)
krd = [duration(KeyRateZero(t), curve, cfs) for t in krd_pillars]

println("Pillar      KRD")
for (t, k) in zip(krd_pillars, krd)
    @printf("  %5.1fy   %12.8f\n", t, k)
end
@printf("\n  Σ KRD    = %12.8f\n", sum(krd))
@printf("  Modified = %12.8f\n", mod_dur)</code></pre>
<div class="cell-output cell-output-stdout">
<pre><code>Pillar      KRD
    1.0y     0.04225406
    2.0y     0.07295018
    3.0y     0.10597903
    4.0y     0.13663542
    5.0y     4.22952272
    6.0y     0.00000000
    7.0y     0.00000000
    8.0y     0.00000000
    9.0y     0.00000000
   10.0y     0.00000000

  Σ KRD    =   4.58734142
  Modified =   4.58732355</code></pre>
</div>
</div>
<p>A 5-year bond has no cashflows past year 5, so the long-end pillars are exactly zero — the right answer, not a bug. The 5y pillar dominates because the principal repayment sits there. And <code>Σ KRD ≈ Modified duration</code> to within the finite-difference noise of the 10 bp internal bump, which is the invariant Ho’s construction is designed to satisfy.</p>
<p>QuantLib doesn’t ship a tent bumper, but it’s emulable: define a <code>ZeroCurve</code> with <code>Linear</code> interpolation across pillar dates, bump one pillar at a time, reprice. Pillar by pillar:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">pillar</th>
<th style="text-align: right;">AU (Ho tent)</th>
<th style="text-align: right;">QL (ZeroCurve bump)</th>
<th style="text-align: right;">diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 y</td>
<td style="text-align: right;">0.04225406</td>
<td style="text-align: right;">0.03749135</td>
<td style="text-align: right;">+4.76e-03</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 y</td>
<td style="text-align: right;">0.07295018</td>
<td style="text-align: right;">0.07295018</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 y</td>
<td style="text-align: right;">0.10597903</td>
<td style="text-align: right;">0.10597903</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">4 y</td>
<td style="text-align: right;">0.13663542</td>
<td style="text-align: right;">0.13663542</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5 y</td>
<td style="text-align: right;">4.22952272</td>
<td style="text-align: right;">4.22952272</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">6–10y</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Σ</strong></td>
<td style="text-align: right;"><strong>4.58734142</strong></td>
<td style="text-align: right;"><strong>4.58257871</strong></td>
<td style="text-align: right;">+4.76e-03</td>
</tr>
</tbody>
</table>
<p>Interior pillars match to displayed precision; the discrepancy at pillar 1 is an edge-convention difference, not a numerical one. AU’s Ho-1992 tents are <em>flat-left</em> at the first pillar and <em>flat-right</em> at the last, which extends coverage to <code>t = 0</code> and to <code>∞</code> and makes the tents <em>tile the timeline</em> at every interior point. Summing them gives exactly a parallel shift, so <strong>by construction Σ KRD = Modified Duration</strong> — to FD precision under the 10bp internal bump used here, and to machine precision via the AD-through-curve path in the next section. This is the <em>aggregation-preserving</em> convention. The standard market alternative — zero-anchored tents at the extreme pillars, which the QL emulation reproduces — instead leaves a gap on <code>[0, pillar_1)</code>: the bond’s <code>t = 0.5</code> cashflow sees only half the pillar-1 bump, which shows up as the ~5bp understatement above. The two conventions answer slightly different questions, and the aggregation-preserving one is the right answer when you need asset-and-liability KRD vectors to sum cleanly into the portfolio-level duration.</p>
<p>(<code>KeyRatePar</code> is also available — same API, par-curve bump, same flat-left/flat-right edges.)</p>
</section>
<section id="the-whole-sensitivity-bundle-in-one-call" class="level2">
<h2 class="anchored" data-anchor-id="the-whole-sensitivity-bundle-in-one-call">The whole sensitivity bundle in one call</h2>
<p>ActuaryUtilities’ <code>sensitivities(zrc, cfs)</code> returns the value, the per-pillar modified-duration vector, <em>and</em> the per-pillar convexity matrix from a single second-order AD pass:</p>
<div id="16" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>zero_rates = [0.02, 0.025, 0.028, 0.030, 0.032, 0.034]
tenors = [1.0, 2.0, 3.0, 5.0, 7.0, 10.0]
zrc = FinanceModels.ZeroRateCurve(zero_rates, tenors)

result = sensitivities(zrc, cfs)

@printf("price                  = %.6f\n", result.value * par)
println("durations by pillar    = ", round.(result.durations; digits=6))
@printf("Σ durations            = %.6f   (≈ total Modified duration)\n",
    sum(result.durations))
@printf("Σ convexities (matrix) = %.6f   (≈ total convexity)\n",
    sum(result.convexities))</code></pre>
<div class="cell-output cell-output-stdout">
<pre><code>price                  = 104.616990
durations by pillar    = [0.040687, 0.075465, 0.150771, 4.32126, 0.00124, 0.0]
Σ durations            = 4.589423   (≈ total Modified duration)
Σ convexities (matrix) = 22.209804   (≈ total convexity)</code></pre>
</div>
</div>
<p>Each entry of <code>result.durations</code> is the bond’s sensitivity at that specific pillar — the same KRD vector from the previous section, recomputed by direct AD through the curve construction instead of by tent bumps. The full convexity <em>matrix</em> (6×6 here) gives cross-pillar second-order effects: <code>result.convexities[i, j]</code> is <code>∂²price / ∂z_i ∂z_j</code>. There is no “sensitivity mode” anywhere in the library; <code>ZeroRateCurve</code> and <code>pv</code> are ordinary functions that happen to be generic on numeric types, and <code>sensitivities</code> bundles the value, gradient, and Hessian.</p>
<p>The same Float64 code path runs in <code>BigFloat</code> for validation, <code>ForwardDiff.Dual</code> for nested AD, <code>Measurements.Measurement</code> for uncertainty propagation — any numeric type that implements arithmetic:</p>
<div id="18" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>yield_big = FinanceModels.Yield.Constant(Continuous(big"0.03"))
cfs_big = collect(FinanceModels.Bond.Fixed(big"0.04", Periodic(2), 5))
duration(Modified(), yield_big, cfs_big)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>4.592215959206013517692818226598484659134894077030275768293407244010322839862452</code></pre>
</div>
</div>
<p>With QuantLib the entire library is <code>double</code>; raising precision is a library fork.</p>
<p>The composability does have limits worth naming. <code>ForwardDiff</code> walks through whatever Julia code you write <em>as long as</em> the code stays in generic-numeric territory — Float64 type pins, in-place mutation, and FFI calls into non-Dual-aware solvers (some configurations of <code>Optim.LBFGS</code>, certain root-finders) break the chain. FinanceModels’ own interfaces are written to be AD-friendly throughout; the caveats are about user code that reaches outside the library.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Under the hood: writing your own AD pipeline
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If <code>sensitivities</code> doesn’t bundle exactly what you want — different curve type, different valuation function, mixed asset/liability portfolio — write the AD call directly:</p>
<div id="20" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>function price_from_zeros(rates)
    curve = FinanceModels.ZeroRateCurve(rates, tenors)
    return FinanceCore.pv(curve, cfs) * par
end

ForwardDiff.gradient(price_from_zeros, zero_rates)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>6-element Vector{Float64}:
   -4.256516955631077
   -7.894971387712997
  -15.773233060924778
 -452.0771850662052
   -0.12969630086592504
   -3.5487356943063716e-14</code></pre>
</div>
</div>
<p>The same <code>ForwardDiff.Dual</code> mechanism, the same numbers as <code>result.durations * (-1) * value * par</code> (sign and scaling from how <code>sensitivities</code> normalizes). Wraps cleanly with <code>Optimization.jl</code> for calibration with an exact gradient, <code>Measurements.Measurement</code> for error bars, another <code>ForwardDiff.gradient</code> for the Hessian.</p>
</div>
</div>
</div>
</section>
<section id="when-the-cashflows-respond-to-rates" class="level2">
<h2 class="anchored" data-anchor-id="when-the-cashflows-respond-to-rates">When the cashflows respond to rates</h2>
<p>Everything so far assumed the cashflow vector was <em>fixed</em>. That’s a fine assumption for a Treasury bond. It’s the wrong assumption for everything actually interesting in an ALM book: callable bonds, prepayable mortgages, life-insurance liabilities with dynamic lapse behavior, GICs with surrender options. The policyholder or borrower has an option whose exercise correlates with rates, and the cashflows on the page are a <em>function</em> of the curve you’re trying to price them against.</p>
<p>The simplest non-trivial case is a level-pay mortgage pool with a constant conditional prepayment rate (CPR). The pass-through cashflow generator is the standard factor model: the underlying mortgage amortizes on its original schedule, and each period a fraction <code>cpr</code> of the surviving balance prepays voluntarily on top of the scheduled cashflow.</p>
<div id="22" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>using FinanceCore: Cashflow

function passthrough_cfs(wac, balance, term, cpr)
    payment = balance * wac / (1 - (1 + wac)^(-term))
    sched_bal = balance
    factor = one(cpr)
    map(1:term) do t
        sched_int = sched_bal * wac
        sched_prin = payment - sched_int
        sched_bal_end = sched_bal - sched_prin
        cf = factor * payment + factor * cpr * sched_bal_end
        factor *= one(cpr) - cpr
        sched_bal = sched_bal_end
        Cashflow(cf, Float64(t))
    end
end

wac_m, term_m, bal_m = 0.05, 10, 100.0
y_market = 0.04
yj_market = FinanceModels.Yield.Constant(Continuous(y_market))

cfs_static = passthrough_cfs(wac_m, bal_m, term_m, 0.06)
(price=FinanceCore.pv(yj_market, cfs_static),
    mod_dur=duration(Modified(), yj_market, cfs_static),
    convexity=convexity(yj_market, cfs_static))</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(price = 103.90084299095979, mod_dur = 4.385847270460361, convexity = 31.040197945986055)</code></pre>
</div>
</div>
<p>Fifteen lines of ordinary code; the output is an ordinary <code>Vector{Cashflow}</code>. Every primitive from the previous sections — <code>pv</code>, <code>duration</code>, <code>convexity</code>, <code>sensitivities</code> — works on it without modification. The mortgage is at a premium (gross coupon 5%, market yield 4%), so as the prepayment assumption rises the price drops toward par — the textbook MBS sensitivity, and a useful sanity check:</p>
<div id="24" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>[(cpr=c, price=FinanceCore.pv(yj_market, passthrough_cfs(wac_m, bal_m, term_m, c)))
 for c in (0.0, 0.06, 0.20, 0.99)]</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>4-element Vector{@NamedTuple{cpr::Float64, price::Float64}}:
 (cpr = 0.0, price = 104.61713397426567)
 (cpr = 0.06, price = 103.90084299095979)
 (cpr = 0.2, price = 102.7490108388589)
 (cpr = 0.99, price = 100.89076822962653)</code></pre>
</div>
</div>
<p>The <em>interesting</em> thing about a prepayment-sensitive asset is that CPR isn’t a constant. When rates fall, refinancing accelerates and CPR rises. Write a refi-incentive model as ordinary Julia, slot it into the price function, and <code>ForwardDiff</code> walks the analytic derivative through <em>both</em> the discounting <em>and</em> the prepayment response:</p>
<div id="26" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>function price_with_refi(y; base=0.06, sens=2.0, wac_ref=0.05)
    cpr = base + sens * max(zero(y), wac_ref - y)
    cfs = passthrough_cfs(wac_m, bal_m, term_m, cpr)
    return FinanceCore.pv(FinanceModels.Yield.Constant(Continuous(y)), cfs)
end

P0_oa = price_with_refi(y_market)
model_dur = -ForwardDiff.derivative(price_with_refi, y_market) / P0_oa
model_conv = ForwardDiff.derivative(
    z -&gt; ForwardDiff.derivative(price_with_refi, z), y_market) / P0_oa

(price=P0_oa, model_duration=model_dur, model_convexity=model_conv)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(price = 103.69674707565362, model_duration = 3.9712193184555766, model_convexity = -19.163381796077413)</code></pre>
</div>
</div>
<p>Model-based duration ~3.97 (shorter than the static 4.39 — the prepayment response chips away at rate sensitivity). Model-based convexity <em>negative</em> — faster prepayment as rates fall caps the upside in price, the canonical MBS signature. Both numbers are exact derivatives of <em>your</em> prepayment model; the AD pass replaces the bump-and-reprice loop you would otherwise write by hand. For ALM and hedging workflows where the prepayment model is part of the assumption set, this is the gradient you actually need. For a trading-desk OAS that captures the option’s <em>vega</em> under a calibrated short-rate process with vol surface, that’s a different number — see the QuantLib section near the end of the post.</p>
<p>The pattern generalises immediately: a dynamic lapse model on an insurance liability, a stochastic mortality assumption on a life annuity, a credit-rating-conditioned default model on a corporate bond. Anything you can write as a differentiable Julia function of the curve composes with <code>ForwardDiff.derivative</code> for parallel sensitivities or <code>.gradient</code> for pillar-wise KRDs. (Non-smooth empirical models — published S-curves with discrete burnout segments, table-driven lapse functions — need a smoothed version, or a finite-difference fallback at the kinks, for the AD chain to work cleanly.) The library never has to know what your model is.</p>
<p>The QL equivalent for the static case is <code>AmortizingFixedRateBond</code> with a custom cashflow <code>Leg</code>. The cashflow-generator logic looks similar; what differs is that sensitivities to the prepayment model require bump-and-recompute by hand, which AD does implicitly here.</p>
</section>
<section id="stochastic-short-rate-models" class="level2">
<h2 class="anchored" data-anchor-id="stochastic-short-rate-models">Stochastic short-rate models</h2>
<p>FinanceModels ships first-class stochastic short-rate models: <code>ShortRate.Vasicek</code>, <code>ShortRate.CoxIngersollRoss</code>, <code>ShortRate.HullWhite</code>. Each implements closed-form ZCB prices, so <code>discount</code> and <code>present_value</code> work on them like any other yield model. <code>simulate</code> generates paths via Euler-Maruyama and wraps each scenario as a <code>RatePath &lt;: AbstractYieldModel</code> — so a scenario <em>is</em> a yield curve, and the existing valuation machinery prices contracts against it without modification. <code>pv_mc</code> averages it across the scenario set:</p>
<div id="28" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>using FinanceModels: ShortRate, simulate
using Random, Statistics

hw = ShortRate.HullWhite(0.05, 0.01, yj_market)   # mean-rev a, vol σ, calibrating curve
rng = Random.MersenneTwister(42)
paths = simulate(hw; n_scenarios=10_000, timestep=1 / 12, horizon=10.0, rng)
hw_pvs = [FinanceCore.present_value(p, cfs_static) for p in paths]

(deterministic=FinanceCore.pv(yj_market, cfs_static),
    hull_white_mc=mean(hw_pvs),
    mc_standard_error=std(hw_pvs) / sqrt(length(hw_pvs)))</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(deterministic = 103.90084299095979, hull_white_mc = 103.91240316350645, mc_standard_error = 0.05333609072986593)</code></pre>
</div>
</div>
<p>Under a flat calibrating curve and σ = 1% the MC mean sits a few cents above the deterministic, with an MC standard error of comparable size — read: the gap is <em>consistent with</em> a small Jensen’s-inequality correction from rate volatility, but at this σ the signal isn’t large versus the MC noise. A realistic 2026 calibration would put σ in the 80–120bp range, where the correction is comfortably outside the SE. The composition itself is the takeaway: <code>simulate</code> produces yield-curve scenarios, <code>present_value</code> prices contracts against them, and the existing valuation machinery handles the rest. Closed-form <code>present_value</code> is also available under the Gaussian models for ZCB calls and puts, caps, floors, and Jamshidian-decomposed European swaptions.</p>
<p>The asymmetric capability: <code>simulate</code> threads <code>ForwardDiff.Dual</code> types, so <code>ForwardDiff.derivative</code> walks <em>through</em> the Monte Carlo PV — model-parameter sensitivities under a stochastic process, no bumping, no separate Greek path. Here’s the same setup wrapped in an AD call against Vasicek’s initial short rate, returning a stochastic-model duration:</p>
<div id="30" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>function pv_mc_vasicek_r0(r0)
    rng = Random.MersenneTwister(42)
    v = ShortRate.Vasicek(0.10, 0.04, 0.01, Continuous(r0))
    ps = simulate(v; n_scenarios=5_000, timestep=1 / 12, horizon=10.0, rng)
    return sum(FinanceCore.present_value(p, cfs_static) for p in ps) / 5_000
end

r0_base = 0.04
P_vas = pv_mc_vasicek_r0(r0_base)
dPdr0_vas = ForwardDiff.derivative(pv_mc_vasicek_r0, r0_base)

(pv=P_vas,
    dpv_dr0=dPdr0_vas,
    stochastic_model_duration=-dPdr0_vas / P_vas)</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(pv = 104.0763581009187, dpv_dr0 = -345.3951879065837, stochastic_model_duration = 3.3186709662886913)</code></pre>
</div>
</div>
<p>Same common-random-numbers seed across the value and the gradient, so the derivative is the pathwise sensitivity rather than a bumped finite difference. The gradient itself carries MC noise (it’s the average of per-path derivatives), so for production you’d report it with an SE the same way as the price. The capability extends naturally to gradients w.r.t. other model parameters (mean reversion, vol) and to multi-parameter <code>gradient</code> calls; some of those require a small array-typing enhancement on the FM side that’s straightforward but not yet shipped.</p>
<p>QL fundamentally can’t do any of this through Python, because the FFI boundary breaks the AD chain. For MC-based calibration objectives with exact gradients, or pathwise sensitivities under a short-rate model, JA is ahead of QL by capability, not by speed.</p>
<p>What FM lacks is the <em>lattice</em> layer: there’s no trinomial-tree engine for early-exercise payoffs, no built-in Longstaff-Schwartz for American Monte Carlo, no multi-factor models like G2++ or LMM, and no calibrator against a swaption-cube vol surface. For a Bermudan callable bond valued under a calibrated short-rate model with market vols, QL’s tree engine is still the right tool. The QL-only territory is more precisely <em>lattice-based early-exercise valuation under stochastic rates</em>, rather than stochastic rates in general, which JA handles directly.</p>
</section>
<section id="performance" class="level2">
<h2 class="anchored" data-anchor-id="performance">Performance</h2>
<p>Pure raw C++ vs Julia isn’t the interesting comparison (QL’s internal C++ is fast). The <em>practical</em> path most users take is QL through its Python SWIG bindings, where each Python→C++ crossing costs hundreds of nanoseconds of object marshaling. FinanceModels is pure Julia with no FFI boundary.</p>
<p>Four representative workloads on the same 5y semi-annual bond, benchmarked against a flat 3% reference yield so the comparison to QL’s <code>FlatForward</code> setup is apples-to-apples (term-structured <code>ZeroRateCurve</code> adds spline-reconstruction overhead per call, which is a separate axis):</p>
<div id="32" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>using BenchmarkTools

b_price = @benchmark FinanceCore.pv($yield_flat, $cfs)
b_mod = @benchmark duration(Modified(), $yield_flat, $cfs)
b_conv = @benchmark convexity($yield_flat, $cfs)

# 30-pillar KRD: build a flat 30-pillar ZeroRateCurve and ask for the whole
# vector in one AD pass.
krd_pillars_30 = collect(1.0:1.0:30.0)
zrc_30 = FinanceModels.ZeroRateCurve(fill(0.03, 30), krd_pillars_30)
b_krd = @benchmark duration(KeyRates(), $zrc_30, $cfs)

(price=minimum(b_price).time,
    mod_duration=minimum(b_mod).time,
    convexity=minimum(b_conv).time,
    krd_30=minimum(b_krd).time)   # ns</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(price = 24.99097291875627, mod_duration = 273.81063122923587, convexity = 301.5381526104418, krd_30 = 4381.0)</code></pre>
</div>
</div>
<p>QuantLib-Python via <code>timeit</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 63%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>Workload — JA call / QL call</th>
<th>FinanceModels (Julia)</th>
<th>QuantLib (Python)</th>
<th>factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bond price — <code>FinanceCore.pv</code> / <code>bond.NPV()</code></td>
<td>~25 ns</td>
<td>~235 ns</td>
<td>~9×</td>
</tr>
<tr class="even">
<td>Modified duration — <code>duration(Modified(), …)</code> / <code>BondFunctions.duration</code></td>
<td>~215 ns (AD)</td>
<td>~1.25 μs</td>
<td>~6×</td>
</tr>
<tr class="odd">
<td>Convexity — <code>convexity</code> / <code>BondFunctions.convexity</code></td>
<td>~255 ns (nested AD)</td>
<td>~1.25 μs</td>
<td>~5×</td>
</tr>
<tr class="even">
<td>30-pillar KRD — <code>duration(KeyRates(), zrc, cfs)</code> / parallel <code>FlatForward</code> bumps</td>
<td>~4 μs (single AD pass)</td>
<td>~385 μs</td>
<td>~95×</td>
</tr>
<tr class="odd">
<td>30-pillar KRD — <code>duration(KeyRates(), zrc, cfs)</code> / per-pillar <code>ZeroCurve</code> bumps</td>
<td>~4 μs (single AD pass)</td>
<td>~1170 μs</td>
<td>~290×</td>
</tr>
</tbody>
</table>
<p>Two things drive the gap. First, <strong>the Python boundary, not the C++ math</strong>: every QL call dispatched from Python costs ~200–300 ns of object marshaling regardless of what’s on the other side. For single-instrument metrics — price, duration, convexity — the actual C++ work is fast enough that the boundary cost dominates, which is why all three rows land in the same 5–9× neighborhood. Duration and convexity both clock in at ~1.25 μs because they’re the same shape from Python’s perspective: one bond, one <code>InterestRate</code>, one C++ function call, one returned scalar.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Is the ~200–300 ns Python boundary fundamental, or just SWIG?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A bit of both. There is a floor every Python↔︎C++ binding pays — and SWIG sits notably above it.</p>
<p><strong>Fundamental floor (~50–100 ns).</strong> Every Python→C call has to acquire and release the GIL, convert each argument from <code>PyObject*</code> to its C/C++ type, reference-count any returned objects, and translate exceptions across the boundary. Even a hand-tuned binding can’t get below this without leaving the CPython interpreter entirely.</p>
<p><strong>SWIG-specific overhead (~100–200 ns on top).</strong> SWIG is a code generator that targets <em>many</em> languages (Python, Ruby, Java, C#, R, Perl, …) from one <code>.i</code> interface file. To stay generic, the wrappers it emits route through a runtime type-resolution table, do extra checked casts, and hop through an extra C shim layer before reaching the C++ method. That’s roughly what doubles QL’s per-call cost relative to a hand-tuned binding.</p>
<p>For comparable single-instrument calls:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Binding strategy</th>
<th>Per-call cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SWIG</strong> (what QuantLib ships)</td>
<td>~200–300 ns</td>
</tr>
<tr class="even">
<td><strong><a href="https://pybind11.readthedocs.io/">pybind11</a></strong> (hypothetical re-binding)</td>
<td>~100 ns</td>
</tr>
<tr class="odd">
<td><strong><a href="https://nanobind.readthedocs.io/">nanobind</a></strong> (modern, AOT-typed)</td>
<td>~50–70 ns</td>
</tr>
<tr class="even">
<td>C++ → C++ direct call</td>
<td>~1–5 ns</td>
</tr>
</tbody>
</table>
<p>A <code>pybind11</code> rewrite of QuantLib could plausibly halve its per-call cost; <code>nanobind</code> could shave a bit more. Neither closes the gap to a native call — they just move the boundary tax from ~200 ns down to ~70 ns, which still dominates tight per-instrument loops.</p>
<p><strong>Why does QL still ship SWIG, then?</strong> It pre-dates pybind11 (the QL-SWIG project goes back to the early 2000s), and the same <code>.i</code> file generates Python, Ruby, Java, C#, R, and Perl bindings. For a library with QL’s reach and longevity, language coverage beat peak per-call speed — a sensible trade in 2003, just one that’s become visible now that the C++-side gap has closed on at least one of those target languages.</p>
</div>
</div>
</div>
<p>Second, <strong>AD bundles all 30 pillar partials into one forward pass</strong>, while QL has to run the bond-pricing engine 60 times (30 pillars × 2 sides). The ~1170 μs figure for the per-pillar <code>ZeroCurve</code> approach is dominated by rebuilding the curve object on every call; the cheaper <code>FlatForward</code> path still pays the per-pillar repricing cost. The single-call <code>KeyRates()</code> is one <code>ForwardDiff.gradient</code> over a 30-Dual vector — same algorithmic work, no Python boundary in the loop.</p>
<p>A C++ application calling QL directly would recover most of the per-call overhead, and the gap would shrink for the rows that aren’t already algorithm-limited. But that isn’t the comparison most Python or R users actually face — they reach for QL through a binding, and the wrapper cost is part of the workflow.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Per-pillar tent-bump KRDs vs single-pass AD: different perturbation shapes, different numbers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The two functions answer slightly different questions. The difference is in what “shift the curve at pillar <code>i</code>” actually means:</p>
<ul>
<li><strong><code>duration(KeyRateZero(t), …)</code></strong> (the section above) applies a Ho-1992 <strong>tent</strong> perturbation — triangular, peaking at <code>t</code> and ramping to zero at adjacent pillars — and FD-bumps the price. The tent shape is fixed, regardless of how <code>zrc</code> interpolates.</li>
<li><strong><code>duration(KeyRates(), zrc, cfs)</code></strong> returns the partial derivative <code>∂P/∂z_i / P</code> at each pillar. The implicit curve perturbation is whatever the curve’s interpolation produces when <code>zrc.rates[i]</code> moves — a tent for <code>Spline.Linear()</code>, a smooth bump for <code>Spline.MonotoneConvex()</code> (FM’s default), something cubic for <code>Spline.Cubic()</code>.</li>
</ul>
<p>Same 30-pillar setup, same bond, same flat zeros, three different KRD vectors:</p>
<div id="34" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>zrc_lin = FinanceModels.ZeroRateCurve(fill(0.03, 30), krd_pillars_30, Spline.Linear())
krds_ad_lin = duration(KeyRates(), zrc_lin, cfs)         # AD through linear spline
krds_ad_mc = duration(KeyRates(), zrc_30, cfs)          # AD through MonotoneConvex (default)

function krd_tent_loop(yield, cfs, pillars)
    return [duration(KeyRateZero(t), yield, cfs, eachindex(cfs), pillars) for t in pillars]
end
krds_tent = krd_tent_loop(yield_flat, cfs, krd_pillars_30)

[krd_pillars_30 krds_tent krds_ad_lin krds_ad_mc][1:7, :]</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>7×4 Matrix{Float64}:
 1.0  0.0417208  0.0417208  0.0430005
 2.0  0.0719629  0.0719628  0.0685591
 3.0  0.10482    0.10482    0.104945
 4.0  0.135672   0.135671   0.147962
 5.0  4.23806    4.23804    4.22148
 6.0  0.0        0.0        0.00627044
 7.0  0.0        0.0        0.0</code></pre>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">pillar</th>
<th style="text-align: right;">tent-bump</th>
<th style="text-align: right;">AD (Linear)</th>
<th style="text-align: right;">AD (MonotoneConvex)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 y</td>
<td style="text-align: right;">0.04172</td>
<td style="text-align: right;">0.04172</td>
<td style="text-align: right;">0.04300</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 y</td>
<td style="text-align: right;">0.07196</td>
<td style="text-align: right;">0.07196</td>
<td style="text-align: right;">0.06856</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 y</td>
<td style="text-align: right;">0.10482</td>
<td style="text-align: right;">0.10482</td>
<td style="text-align: right;">0.10495</td>
</tr>
<tr class="even">
<td style="text-align: right;">4 y</td>
<td style="text-align: right;">0.13567</td>
<td style="text-align: right;">0.13567</td>
<td style="text-align: right;">0.14796</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5 y</td>
<td style="text-align: right;">4.23806</td>
<td style="text-align: right;">4.23804</td>
<td style="text-align: right;">4.22148</td>
</tr>
<tr class="even">
<td style="text-align: right;">6 y</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00627</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Σ</strong></td>
<td style="text-align: right;"><strong>4.59223</strong></td>
<td style="text-align: right;"><strong>4.59222</strong></td>
<td style="text-align: right;"><strong>4.59222</strong></td>
</tr>
</tbody>
</table>
<p>Three things to notice:</p>
<ol type="1">
<li><p><strong>Tent-bump and AD-through-Linear agree to FD precision.</strong> That’s not a coincidence — perturbing a linearly-interpolated curve’s pillar IS a tent. Same calculation, two routes.</p></li>
<li><p><strong>AD-through-MonotoneConvex gives different per-pillar numbers.</strong> The MC-shape perturbation reaches further than a tent — its “tail” smooths past the last cashflow date, which is why pillar 6 carries 6bp of duration even though the bond pays nothing after year 5. Inside the cashflow range, the attribution is shifted: less weight at year 5, more at year 4, less at year 2, more at year 1.</p></li>
<li><p><strong>Σ KRD = Modified duration in all three.</strong> The aggregation invariant doesn’t care which perturbation shape you used — the sum recovers the parallel-shift duration regardless. What differs is <em>how that total is attributed across pillars</em>.</p></li>
</ol>
<p>Pick whichever decomposition your downstream risk system expects: Bloomberg-style tent bumps for portfolios where matching counterparty risk reports matters, AD-through-curve for ALM workflows where the curve’s interpolation IS the model.</p>
<p>Timing the tent-bump loop on the same setup:</p>
<div id="36" class="cell" data-execution_count="1">
<pre class="julia cell-code"><code>b_krd_tent = @benchmark krd_tent_loop($yield_flat, $cfs, $krd_pillars_30)
minimum(b_krd_tent).time   # ns</code></pre>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>30250.0</code></pre>
</div>
</div>
<p>~26 μs per 30-pillar vector — about 6× slower than the single AD pass under MonotoneConvex, still 15× faster than QL’s cheapest per-pillar emulation.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The QuantLib benchmark code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre class="python"><code># Python — QuantLib benchmark reference code
import QuantLib as ql
import timeit, math

settle    = ql.Date(1, 1, 2026)
maturity  = ql.Date(1, 1, 2031)
ql.Settings.instance().evaluationDate = settle
day_count = ql.Thirty360(ql.Thirty360.BondBasis)
schedule  = ql.Schedule(settle, maturity, ql.Period(ql.Semiannual),
                        ql.NullCalendar(), ql.Unadjusted, ql.Unadjusted,
                        ql.DateGeneration.Backward, False)
bond      = ql.FixedRateBond(0, 100.0, schedule, [0.04], day_count)
ytm       = 0.03

flat = ql.FlatForward(settle, ql.QuoteHandle(ql.SimpleQuote(ytm)),
                      day_count, ql.Continuous)
bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(flat)))

# Native duration / convexity take an InterestRate built from an annual-compounded rate
y_ann = math.exp(0.03) - 1
ir    = ql.InterestRate(y_ann, day_count, ql.Compounded, ql.Annual)

timeit.timeit(lambda: bond.NPV(),                                                number=10_000)
timeit.timeit(lambda: ql.BondFunctions.duration(bond, ir, ql.Duration.Modified), number=10_000)
timeit.timeit(lambda: ql.BondFunctions.convexity(bond, ir),                      number=10_000)

# 30-pillar KRD setup
pillars         = list(range(1, 31))
pillar_dates_30 = [settle + ql.Period(y, ql.Years) for y in pillars]
flat_zeros_30   = [0.03] * len(pillars)
shift           = 1e-3

# (a) lower-bound: parallel FlatForward bumps repeated per pillar
def krd_flatforward():
    out = []
    for _ in pillars:
        up = ql.FlatForward(settle, ql.QuoteHandle(ql.SimpleQuote(ytm + shift)),
                            day_count, ql.Continuous)
        dn = ql.FlatForward(settle, ql.QuoteHandle(ql.SimpleQuote(ytm - shift)),
                            day_count, ql.Continuous)
        bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(up)))
        p_up = bond.NPV()
        bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(dn)))
        p_dn = bond.NPV()
        out.append((p_dn - p_up) / (2 * shift * 100))
    bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(flat)))
    return out

# (b) representative: ZeroCurve bump-and-rebuild, one pillar at a time
def krd_zerocurve():
    out = []
    for i in range(len(pillars)):
        up = flat_zeros_30[:];  up[i] += shift
        dn = flat_zeros_30[:];  dn[i] -= shift
        zc_up = ql.ZeroCurve(pillar_dates_30, up, day_count, ql.NullCalendar(),
                             ql.Linear(), ql.Continuous)
        zc_dn = ql.ZeroCurve(pillar_dates_30, dn, day_count, ql.NullCalendar(),
                             ql.Linear(), ql.Continuous)
        bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(zc_up)))
        p_up = bond.NPV()
        bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(zc_dn)))
        p_dn = bond.NPV()
        out.append((p_dn - p_up) / (2 * shift * 100))
    bond.setPricingEngine(ql.DiscountingBondEngine(ql.YieldTermStructureHandle(flat)))
    return out

timeit.timeit(krd_flatforward, number=1_000)
timeit.timeit(krd_zerocurve,   number=1_000)</code></pre>
</div>
</div>
</div>
</section>
<section id="when-youd-reach-for-quantlib-instead" class="level2">
<h2 class="anchored" data-anchor-id="when-youd-reach-for-quantlib-instead">When you’d reach for QuantLib instead</h2>
<p>The gap between the two libraries is narrower than it was a few years ago — FinanceModels has caught up on Gaussian short-rate machinery, AD-friendly Monte Carlo, and the kind of sensitivity tooling actuarial workflows actually use. The remaining QL-only territory is concentrated in the <em>trading-desk</em> corner: lattice and tree engines for early-exercise payoffs (Bermudan callable bonds, callable swaptions, American options), multi-factor models (G2++, LMM/BGM), local- and stochastic-volatility for equity and FX (Heston, SABR, Bates, displaced diffusion), calibrators against quoted swaption-cube and cap-surface vols, regional day-count and holiday calendars, full FX curves with cross-currency basis swaps, swap-curve bootstrapping against market quote conventions, credit (Jarrow-Turnbull, hazard-rate), inflation, and commodity term structures. If your daily question is “what’s the price of <em>this specific instrument</em> on <em>this specific settlement date</em> under <em>this specific market’s convention</em>,” QuantLib has thought longer about your question than any open-source alternative.</p>
<p>JuliaActuary’s center of gravity is somewhere else: projecting cashflows forward, fitting curves to observed quotes, computing the sensitivities of those projections to the inputs that drove them, running scenarios through generic numeric types. The instrument universe is narrower and the lattice engines aren’t there yet, but the <em>composability</em> of what’s there is wider — and on the stochastic side, JA’s <code>simulate</code> is AD-friendly in a way QL’s Python-wrapped engines can’t be. For an ALM reporting workflow that runs nightly on a known book — vanilla and structured bonds, calibrated curves, duration and KRD vectors, accounting attribution, sensitivities used as inputs to a downstream optimization — the JA stack tends to win on the parts of the calculation that aren’t already algorithm-limited. The win is fewer numerical knobs, exact derivatives, and generic types, all in one Julia binary rather than a Python-bound C++ library with a separate calibration runtime sitting next to it.</p>
<p>The two libraries aren’t really competing for the same job. They’re optimized for adjacent jobs that happen to share a vocabulary.</p>
<hr>
<p>The <code>cfs</code> defined at the top of this post threaded through every example: price, Macaulay and Modified duration, convexity, ten KRDs, a 30-pillar KRD benchmark, the second-order sensitivity through a calibrated zero curve, the prepayment-sensitive mortgage pool with refi response, the Hull-White Monte Carlo. The library never needed a sensitivity-specific API or an AD-aware override; generic numeric types flowed through ordinary functions, and <code>ForwardDiff</code> extracted whatever derivative each step needed.</p>
<p>That’s the part that’s hard to retrofit into a framework written before automatic differentiation became cheap.</p>
<p><strong>One vector of cashflows. One curve. The rest is just ordinary Julia.</strong></p>
<hr>
<p><em>Drafted with the assistance of an AI coding agent (Anthropic’s Claude) under my direction. All code chunks execute at render time; QuantLib reference numbers were generated from the Python snippets shown inline.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/JuliaActuary\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>